spring:
  application:
    name: modulo4.2

  cloud:
    function:
      definition: pessoaConsumer

    stream:
      bindings:
        pessoaConsumer-in-0:
          destination: pessoa.atualizada
          group: pessoa-group1
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092, localhost:9093, localhost:9094
          auto-create-topics: true

        bindings:
          pessoaConsumer-in-0:
            consumer:
              auto-offset-reset: earliest
              enableDlq: true
